CVGS/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CVGS.Models;

namespace CVGS.Controllers {
    public class GameController : Controller
    {
        private ConestogaVideogameStoreDbContext db = new ConestogaVideogameStoreDbContext();

        // GET: Game
        public ActionResult Index() {
            return View(db.Game.ToList());
        }

        // GET: Game/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            if (game == null) {
                return HttpNotFound();
            }
            return View(game);
        }

        // GET: Game/Create
        public ActionResult Create()
        {
            Game g = db.Game.ToList().Last();
            ViewBag.id = g.id + 1 + "";
            return View();
        }

        // POST: Game/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,genre,releaseDate,developer,esrbRating,details,plot")] Game game) {
            if (ModelState.IsValid) {
                db.Game.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(game);
        }

        // GET: Game/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            if (game == null) {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Game/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,genre,releaseDate,developer,esrbRating,details,plot")] Game game) {
            if (ModelState.IsValid) {
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(game);
        }

        // GET: Game/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Game.Find(id);
            if (game == null) {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Game/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            Game game = db.Game.Find(id);
            db.Game.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddReview(int? gameId, int? userId) {
            return RedirectToAction("Create", "GameReview", new { gameId = gameId, userId = userId });
        }

        public ActionResult ViewGameReviews(int? gameId) {
            if (!gameId.HasValue) {
                //all reviews of all applicable
                return RedirectToAction("Index", "GameReview");
            }
            if (!db.Game.Any(g => g.id == gameId)) {
                //id does not exist
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //all reviews of 1 game
            return RedirectToAction("GameAllReviews", "GameReview", new { gameId = gameId });
        }

        public ActionResult AddToWishList(int? gameId, int? userId) {
            if (!gameId.HasValue || !userId.HasValue) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!db.Game.Any(g => g.id == gameId) || !db.Member.Any(u => u.id == userId)) {
                //either id does not exist
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return RedirectToAction("Create", "WishList", new { gameId = gameId, userId = userId });
        }

        public ActionResult AddToCart(int? gameId, int? userId)
        {
            if (!gameId.HasValue || !userId.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!db.Game.Any(g => g.id == gameId) || !db.Member.Any(u => u.id == userId))
            {
                //either id does not exist
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return RedirectToAction("Create", "Cart", new { gameId = gameId, userId = userId });
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CVGS/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CVGS.Models;

namespace CVGS.Controllers
{
    public class MemberController : Controller
    {
        private ConestogaVideogameStoreDbContext db = new ConestogaVideogameStoreDbContext();

        // GET: Member
        public ActionResult Index()
        {
            var member = db.Member.Include(u=>u.UserStatus);
            return View(member.ToList());
        }

        // GET: Member/Details/5
        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Member.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        public ActionResult RelativeList(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Member.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var relatives =
                db.RelativeList
                .Where(r => r.Member.id == id)
                .Include(r => r.Relative);
            return View(relatives.ToList());
        }

        public ActionResult AddRelative(int? user1_id, int? user2_id)
        {
            if ((!user1_id.HasValue || !user2_id.HasValue) || (user1_id == user2_id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (user1_id == user2_id)
            {
                return RedirectToAction("RelativeList", new { id = user1_id });
            }
            if (db.RelativeList.Any(rl => rl.user1_id == user1_id && rl.user2_id == user2_id))
            {
                //TODO: add error message
                return RedirectToAction("RelativeList", new { id = user1_id });
            }
            User user1 = db.Member.Find(user1_id);
            User user2 = db.Member.Find(user2_id);
            if (user1 == null || user2 == null)
            {
                return HttpNotFound();
            }
            return View(new List<User> { user1, user2 });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRelative([Bind(Include = "id,user1_id,user2_id")] RelativeList relativeList)
        {
            if (ModelState.IsValid)
            {
                db.RelativeList.Add(relativeList);
                db.RelativeList.Add(new RelativeList { user1_id = relativeList.user2_id, user2_id = relativeList.user1_id });
                db.SaveChanges();

                return RedirectToAction("RelativeList", new { id = relativeList.user1_id });
            }
            return View(new List<User> { db.Member.Find(relativeList.user1_id), db.Member.Find(relativeList.user2_id) });
        }

        // GET: Member/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.userStatusId = new SelectList(db.UserRank, "id", "status");
            User u = db.Member.ToList().LastOrDefault();
            ViewBag.id = u.id + 1 + "";
            return View();
        }

        // POST: Member/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,userStatusId,username,password,givenName,surname,email,phone,address,postalCode,mobile,fax,extension,preferences")] User user)
        {
            if (ModelState.IsValid)
            {
                if (db.Member.Any(u => u.username == user.username))
                {
                    ViewBag.DuplicateUser = "Username taken";
                    return View("Create", user);
                }
                db.Member.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.userStatusId = new SelectList(db.UserRank, "id", "status", user.userStatusId);
            return View(user);
        }

        // GET: Member/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Member.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.userStatusId = new SelectList(db.UserRank, "id", "status", user.userStatusId);
            return View(user);
        }

        // POST: Member/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,userStatusId,username,password,givenName,surname,email,phone,address,postalCode,mobile,fax,extension")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.userStatusId = new SelectList(db.UserRank, "id", "status", user.userStatusId);
            return View(user);
        }

        // GET: Member/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Member.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Member/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Member.Find(id);
            db.Member.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult EditPreferences(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Member.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPreferences([Bind(Include = "id,preferences")] User miduser)
        {
            if (ModelState.IsValid)
            {
                User user = db.Member.Find(miduser.id);
                user.preferences = miduser.preferences;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult SeeWishList(int? id)
        {
            return RedirectToAction("Index", "WishList", new { userId = id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CVGS/Views/GameReview/Create.cshtml
@model CVGS.Models.GameReview

@{
    ViewBag.Title = "Add Review - " + Model.Game.title;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Rate or Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.gameId)
        @Html.HiddenFor(model => model.userId)
        <div class="form-group">
            @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to All Reviews", "Index") |
    @Html.ActionLink("More Reviews for This Game", "GameAllReviews", new { gameId = Model.gameId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CVGS/Views/GameReview/Delete.cshtml
@model CVGS.Models.GameReview

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GameReview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Game.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Game.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.details)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CVGS/Views/GameReview/Details.cshtml
@model CVGS.Models.GameReview

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>GameReview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Game.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Game.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.username)
        </dt>

        <dd>
            @Html.ActionLink(Model.User.username.ToString(), "Details", "Member", new { id = Model.userId }, null)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.details)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("All Reviews", "Index") |
    @Html.ActionLink("More Reviews for This Game", "GameAllReviews", new { gameId = Model.gameId }) |
    @Html.ActionLink("Game Details", "Index", "Game", new { id = Model.gameId }, null)
</p>

CVGS/Views/GameReview/Edit.cshtml
@model CVGS.Models.GameReview

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GameReview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.gameId, "gameId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("gameId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.gameId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userId, "userId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("userId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.details, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CVGS/Views/GameReview/GameAllReviews.cshtml
@model IEnumerable<CVGS.Models.GameReview>

@{
    ViewBag.Title = Model.First().Game.title + " - All Reviews";
}

<h2>@ViewBag.Title</h2>

<p>
    @{
        int id;
        if (Session["userId"] != null)
        {
            id = Int32.Parse(Session["userId"].ToString());
            @Html.ActionLink("Add a Review", "Create", new { gameId = Model.First().gameId, userId = id });
        }
    }
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.userId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.details)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.User.username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.details)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.id })
            </td>
        </tr>
    }
</table>

<p>
    @Html.ActionLink("Back to All Reviews", "Index") |
    @Html.ActionLink("Back to Game Details", "Details", "Game", new { id = Model.First().gameId }, null)
</p>

CVGS/Views/GameReview/Index.cshtml
@model IEnumerable<CVGS.Models.GameReview>

@{
    ViewBag.Title = "Reviews Written by Users";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Game.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.details)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Game.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.details)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>